either/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('questions/', include('questions.urls'))
]

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:q_id>/', views.detail, name='detail'),
    path('<int:q_id>/update/', views.update, name='update'),
    path('<int:q_id>/delete/', views.delete, name='delete'),
    path('<int:q_id>/<int:c_id>/', views.choice_update, name="choice_update"),
    path('<int:q_id>/<int:c_id>/comment',
         views.create_comment, name='create_comment'),

]

questions/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    content = models.CharField(max_length=200)
    choice1 = models.CharField(max_length=200)
    choice2 = models.CharField(max_length=200)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    count = models.IntegerField()


class Comment(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    username = models.CharField(max_length=100)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

questions/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice, Comment
import random
# Create your views here.


def index(request):
    questions = Question.objects.all()

    if questions:
        question = random.choice(questions)
    else:
        question = ''

    context = {
        'question': question
    }
    return render(request, 'index.html', context)


def create(request):
    if request.method == "POST":
        content = request.POST.get('content')
        choice1 = request.POST.get('choice1')
        choice2 = request.POST.get('choice2')

        question = Question.objects.create(
            content=content,
            choice1=choice1,
            choice2=choice2
        )

        c1 = Choice.objects.create(
            question=question,
            content=choice1,
            count=0
        )

        c2 = Choice.objects.create(
            question=question,
            content=choice2,
            count=0
        )

        return redirect('questions:index')
        # question을 만든다
    else:
        return render(request, 'form.html')


def update(request, q_id):
    question = Question.objects.get(id=q_id)

    if request.method == "POST":
        content = request.POST.get('content')
        choice1 = request.POST.get('choice1')
        choice2 = request.POST.get('choice2')

        question.content = content
        question.choice1 = choice1
        question.choice2 = choice2
        question.save()

        choices = question.choice_set.all()
        c1 = choices[0]
        c2 = choices[1]
        c1.content = choice1
        c2.content = choice2

        c1.save()
        c2.save()

        return redirect('questions:detail', q_id)

    else:

        context = {
            'question': question
        }

        return render(request, 'form.html', context)


def detail(request, q_id):
    question = Question.objects.get(id=q_id)

    choices = question.choice_set.all()
    c1 = choices[0]
    c2 = choices[1]
    total = choices[0].count + choices[1].count

    if total == 0:
        c1_ratio = 0
        c2_ratio = 0
    else:
        c1_ratio = round((choices[0].count / total)*100, 2)
        c2_ratio = round((choices[1].count / total)*100, 2)

    context = {
        'question': question,
        'c1': c1,
        'c2': c2,
        'c1_ratio': c1_ratio,
        'c2_ratio': c2_ratio
    }

    return render(request, 'detail.html', context)


def delete(request, q_id):
    question = Question.objects.get(id=q_id)
    question.delete()

    return redirect('questions:index')


def choice_update(request, q_id, c_id):
    choice = Choice.objects.get(id=c_id)
    choice.count += 1
    choice.save()

    return redirect('questions:detail', q_id)


def create_comment(request, q_id, c_id):
    choice = Choice.objects.get(id=c_id)

    username = request.POST.get('username')
    text = request.POST.get('text')

    Comment.objects.create(choice=choice, username=username, text=text)

    return redirect('questions:detail', q_id)

questions/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>either</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'questions:index' %}">B와 D사이의 C 🐓</a>
  </nav>
  <div class="container my-3">
    {% block body %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

questions/templates/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block body %}
<div class="my-3 text-center">
  <a href="{% url 'questions:delete' question.id %}" class='btn btn-danger'>삭제</a>
  <a href="{% url 'questions:update' question.id %}" class='btn btn-warning'>수정</a>
</div>
<h1 class="text-center my-3">🔮 {{question.content}} 🔮</h1>

<div class="row">
  <div class="col" style="height:50vh;">
    <a style="width:100%;height:100%;" href="{% url 'questions:choice_update' question.id c1.id %}"
      class="btn btn-primary">
      <div class="d-flex flex-column justify-content-center" style="height: 100%;">
        <div style="font-size:4rem;">{{c1.content}}</div>
        <!-- <div style="font-size:4rem;">{{c1.count}}</div> -->
        <div style="font-size:4rem;">{{c1_ratio}} %</div>
      </div>
    </a>

    <form action="{% url 'questions:create_comment' question.id c1.id %}" method="POST">
      {%csrf_token%}
      <input type="text" name="username" class="form-control my-1" placeholder="사용자 이름">
      <textarea class="form-control my-1" name="text" id="" cols="30" rows="5" placeholder="댓글을 작성하세요!"></textarea>
      <div class="d-flex justify-content-center">
        <input type='submit' class="btn btn-info mb-2" value="'{{c1.content}}' 의견달기">
      </div>
    </form>

    {% for comment in c1.comment_set.all %}
    <div class="list-group mb-3">
      <a href="#" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{comment.username}}</h5>
          <small>{{comment.created_at|naturaltime}}</small>
        </div>
        <p class="mb-1">{{comment.text}}</p>
      </a>
    </div>
    {% empty%}
    <h4>댓글을 달아주세요!</h4>
    {% endfor %}

  </div>
  <div class="col" style="height:50vh;">
    <a style="width:100%;height:100%;" href="{% url 'questions:choice_update' question.id c2.id %}"
      class="btn btn-danger">
      <div class="d-flex flex-column justify-content-center" style="height: 100%;">
        <div style="font-size:4rem;">{{c2.content}}</div>
        <!-- <div style="font-size:4rem;">{{c2.count}}</div> -->
        <div style="font-size:4rem;">{{c2_ratio}} %</div>
      </div>
    </a>

    <form action="{% url 'questions:create_comment' question.id c2.id %}" method="POST">
      {%csrf_token%}
      <input type="text" name="username" class="form-control my-1" placeholder="사용자 이름">
      <textarea class="form-control my-1" name="text" id="" cols="30" rows="5" placeholder="댓글을 작성하세요!"></textarea>
      <div class="d-flex justify-content-center">
        <input type='submit' class="btn btn-info mb-2" value="'{{c2.content}}' 의견달기">
      </div>
    </form>

    {% for comment in c2.comment_set.all %}
    <div class="list-group mb-3">
      <a href="#" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{comment.username}}</h5>
          <small>{{comment.created_at|naturaltime}}</small>
        </div>
        <p class="mb-1">{{comment.text}}</p>
      </a>
    </div>
    {% empty%}
    <h4>댓글을 달아주세요!</h4>
    {% endfor %}
  </div>
</div>



{% endblock %}

questions/templates/form.html
{% extends 'base.html' %}
{% block body %}

<h3 class="my-3">💀 우리를 곤란하게 할 질문을 남겨보세요!</h3>

<form action="" method='post' class="my-3">
  {% csrf_token %}

  <div class="form-group">
    <label for="content">질문 내용</label>
    <input class="form-control" type="text" id="content" name="content" value="{{question.content}}">
  </div>
  <div class="form-group">
    <label for="choice1">선택1</label>
    <input class="form-control" type="text" id="choice1" name="choice1" value="{{question.choice1}}">
  </div>
  <div class="form-group">
    <label for="choice2">선택2</label>
    <input class="form-control" type="text" id="choice2" name="choice2" value="{{question.choice2}}">
  </div>
  <input class="btn btn-primary" type="submit" value="제출">
</form>

{% endblock %}

questions/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="d-flex flex-column">
  <div class="d-flex justify-content-center">
    <a href="{% url 'questions:create' %}" class="btn btn-primary my-3">
      👀 질 문 생 성 👀
    </a>
  </div>
  {% if question %}
  <a href="{% url 'questions:detail' question.id %}" class="btn btn-info">
    <div class="d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
      <div style="font-size:5rem;">{{question.content}}</div>
      <div style="font-size:5rem;">🔥GO🔥</div>
    </div>
  </a>
  {% else %}
  <h1 class="text-center">!! 질문을 생성해주세요 !!</h1>
  {% endif%}
</div>
{% endblock %}